# -*- coding: utf-8 -*-
"""train

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Nd9RoCLJCHQY395eejlLNvgrhsp48lN
"""

from pathlib import Path
import subprocess
import sys

REPO_DIR = Path(
    "/content/physics-informed-ecostress-downscaling"
)

if not REPO_DIR.exists():
    subprocess.run(
        [
            "git",
            "clone",
            "https://github.com/spancharapula-byte/physics-informed-ecostress-downscaling.git",
            str(REPO_DIR)
        ],
        check=True
    )

sys.path.insert(
    0,
    str(REPO_DIR / "src")
)

print("Model file found:", (REPO_DIR / "src/u_net_model.py").exists())

from pathlib import Path
import json

import numpy as np
import torch
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader
from u_net_model import UNet


# ============================================================
# Paths
# ============================================================

PROJECT_DIR = Path(
    "/content/drive/MyDrive/physics-informed-ecostress-downscaling-main"
)

PROCESSED_DIR = PROJECT_DIR / "data/processed"

TRAIN_PATH = PROCESSED_DIR / "train_dataset.pt"
VAL_PATH = PROCESSED_DIR / "val_dataset.pt"
STATS_PATH = PROCESSED_DIR / "normalization_stats.json"

# This is your writable output folder.
MODEL_DIR = Path(
    "/content/drive/MyDrive/ecostress_model_outputs"
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ============================================================
# Configuration
# ============================================================

BATCH_SIZE = 2
NUM_EPOCHS = 10
LEARNING_RATE = 1e-4
RANDOM_SEED = 42

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

torch.manual_seed(RANDOM_SEED)


# ============================================================
# Load data and normalization statistics
# ============================================================

train_data = torch.load(
    TRAIN_PATH,
    map_location="cpu",
    weights_only=True
)

val_data = torch.load(
    VAL_PATH,
    map_location="cpu",
    weights_only=True
)

with open(STATS_PATH, "r") as file:
    stats = json.load(file)

input_means = torch.tensor(
    stats["input_means"],
    dtype=torch.float32
).view(9, 1, 1)

input_stds = torch.tensor(
    stats["input_stds"],
    dtype=torch.float32
).view(9, 1, 1)

target_mean = float(
    stats["target_mean_K"]
)

target_std = float(
    stats["target_std_K"]
)

print("Training inputs:", train_data["inputs"].shape)
print("Training targets:", train_data["targets"].shape)
print("Validation inputs:", val_data["inputs"].shape)
print("Using device:", DEVICE)


# ============================================================
# Dataset
# ============================================================

class LSTDataset(Dataset):

    def __init__(self, data):
        self.inputs = data["inputs"]
        self.targets = data["targets"]

    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, index):

        x = self.inputs[index].float()
        y = self.targets[index].float()

        # Normalize the nine input channels.
        x = (x - input_means) / input_stds

        # Normalize temperature targets.
        y = (y - target_mean) / target_std

        return x, y


train_dataset = LSTDataset(train_data)
val_dataset = LSTDataset(val_data)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0
)


# ============================================================
# U-Net baseline
# ============================================================

model = UNet(
    in_channels=9,
    out_channels=1
).to(DEVICE)

criterion = nn.MSELoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=LEARNING_RATE
)


# ============================================================
# Training
# ============================================================

best_validation_loss = float("inf")

history = {
    "train_loss": [],
    "validation_loss": []
}

for epoch in range(NUM_EPOCHS):

    model.train()
    total_train_loss = 0.0

    for inputs, targets in train_loader:

        inputs = inputs.to(DEVICE)
        targets = targets.to(DEVICE)

        optimizer.zero_grad()

        predictions = model(inputs)

        loss = criterion(
            predictions,
            targets
        )

        loss.backward()
        optimizer.step()

        total_train_loss += loss.item()

    average_train_loss = (
        total_train_loss / len(train_loader)
    )

    model.eval()
    total_validation_loss = 0.0

    with torch.no_grad():

        for inputs, targets in val_loader:

            inputs = inputs.to(DEVICE)
            targets = targets.to(DEVICE)

            predictions = model(inputs)

            loss = criterion(
                predictions,
                targets
            )

            total_validation_loss += loss.item()

    average_validation_loss = (
        total_validation_loss / len(val_loader)
    )

    history["train_loss"].append(
        average_train_loss
    )

    history["validation_loss"].append(
        average_validation_loss
    )

    print(
        f"Epoch {epoch + 1}/{NUM_EPOCHS} | "
        f"Train: {average_train_loss:.6f} | "
        f"Validation: {average_validation_loss:.6f}"
    )

    if average_validation_loss < best_validation_loss:

        best_validation_loss = average_validation_loss

        torch.save(
            model.state_dict(),
            MODEL_DIR / "best_unet_model.pth"
        )

        print("Best model saved.")


np.save(
    MODEL_DIR / "training_history.npy",
    history,
    allow_pickle=True
)

print("Training complete.")
print(
    "Saved model:",
    MODEL_DIR / "best_unet_model.pth"
)